### ISSUE TITLE
PhP install error

### ISSUE THREAD

**Issue by JolleJolles** [surjeets/Animal_Home_Cage#3]
Hi. I am trying to install your module but get the following error 

```
php: command not found
```

The install log shows the following
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package libapache2-mod-php7.0
E: Couldn't find any package by glob 'libapache2-mod-php7.0'
E: Couldn't find any package by regex 'libapache2-mod-php7.0'
E: Package 'libav-tools' has no installation candidate
awk: cannot open /etc/apache2/ports.conf (No such file or directory)
awk: cannot open /etc/apache2/ports.conf (No such file or directory)
mv: cannot move 'etc/apache2/sites-available/AniHome.conf' to '/etc/apache2/sites-available/AniHome.conf': No such file or directory
ln: failed to create symbolic link '/etc/apache2/sites-enabled/raspicam.conf': No such file or directory
sed: can't read /etc/apache2/conf.d/other-vhosts-access-log: No such file or directory
Failed to restart apache2.service: Unit apache2.service not found.
```

Any simple solution to fix this?

**Comment by surjeets** [comment]
Hi Jolles, what OS are you using?

**Comment by JolleJolles** [comment]
Mac OS (High Sierra)

**Comment by surjeets** [comment]
Hi Jolles, this package works only for Raspbian on Raspberry Pi. To install the OS on Raspberry pi you can use  NOOBS – New Out Of the Box Software – which is an alternative straightforward way to install an operating system. You can download it from here: https://www.raspberrypi.org/downloads/noobs/ 
Once you have your Pi ready, enable Pi camera  then you can install this package and hopefully it will work.

**Comment by surjeets** [comment]
You can read more about our implementation in this manuscript: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0220751

**Comment by JolleJolles** [comment]
Sorry I meant to say I ofcourse encountered the error on my raspberry pi. It is running Raspbian Buster and is fully updated (rpi 3 B+). I tried again using your simple steps but error persists.

Yes, I came upon you package from your paper as I am writing a review on raspberry pi's and wanted to try your package for inclusion.

**Comment by surjeets** [comment]
Hi Jolles, try installing this version of NOOBS:
http://downloads.raspberrypi.org/NOOBS/images/NOOBS-2017-12-01/
Then enable your camera after OS is up (check this settings image), then install our package following instructions given in this repository, please let me know if problem still persists. Due to lock-down I don't have access to my lab else I would have tested it on a RPi right away.

Alternative on your current OS first try: 
step 1: sudo apt-get update
step 2: sudo apt-get dist-upgrade
step 3: sudo apt install libapache2-mod-php
(it should pull in php7 as a dependency)

If this throws an error then try 
sudo apt-get install php7.0 

![enable-raspberry-pi-camera](https://user-images.githubusercontent.com/11226511/81043906-77772600-8e70-11ea-9665-1114bc5e5697.jpg)

**Comment by rfkova** [comment]
Hi there,

I've got a similar problem trying to run this code. I tried the suggested remedies but didn't work out. Here's the relevant info (below). Any suggestions would be very welcome! My camera works and is enabled. 

Best,
Ryan

OPERATING SYSTEM VIA “cat /etc/os-release”

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

CHECKING UPDATES PER RECOMENDATION
pi@raspberrypi:~ $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian buster InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease
Reading package lists... Done                              
pi@raspberrypi:~ $ sudo apt-get dist-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ sudo apt install libapache2-mod-php
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libapache2-mod-php is already the newest version (2:7.3+69).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

INSTALL ATTEMPT
pi@raspberrypi:~/Animal_Home_Cage $ ./install.sh

OFFERS CONFIG OPTIONS

 Copyright (c) 2017, Surjeet Singh. AniHome v1.1.10
 ───────────────────────────────────────────────────────────────────────────────────────








                 ┌──────────────Configuration Options────────────────┐
                 │ ┌───────────────────────────────────────────────┐ │  
                 │ │AniHome subfolder:             html            │ │  
                 │ │Autostart:(yes/no)             yes             │ │  
                 │ │Server:(apache/nginx/lighttpd) apache          │ │  
                 │ │Webport:                       80              │ │  
                 │ │User:(leave blank)                             │ │  
                 │ │Password: (leave blank)                        │ │  
                 │ │jpglink:(yes/no)               yes             │ │  
                 │ │phpversion:(5/7)               7               │ │  
                 │ └───────────────────────────────────────────────┘ │  
                 │                                                   │  
                 ├───────────────────────────────────────────────────┤  
                 │             <  OK  >       <Cancel>               │  
                 └───────────────────────────────────────────────────┘  
                   

CLICK “OK”
Reading package lists... Done

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'php7.0-thrift' for regex 'php7.0'
Note, selecting 'php7.0-remctl' for regex 'php7.0'
Note, selecting 'php7.0-common' for regex 'php7.0'
Note, selecting 'php7.0-curl' for regex 'php7.0'
Note, selecting 'php-remctl' instead of 'php7.0-remctl'
Package libav-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  ffmpeg

E: Unable to locate package php7.0-cli
E: Couldn't find any package by glob 'php7.0-cli'
E: Couldn't find any package by regex 'php7.0-cli'
E: Unable to locate package libapache2-mod-php7.0
E: Couldn't find any package by glob 'libapache2-mod-php7.0'
E: Couldn't find any package by regex 'libapache2-mod-php7.0'
E: Package 'libav-tools' has no installation candidate
Your custom raspimjpg backed up at /etc/raspimjpeg.bak
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
sed: can't read /etc/motion/motion.conf: No such file or directory
chown: invalid user: ‘motion:www-data’
chmod: cannot access '/etc/motion/motion.conf': No such file or directory

THEN IT ASKS TO START CAMERA SYSTEM, BUT CHOOSING “YES” DOES NOTHING...

**Comment by johndoe2309** [comment]
Hi surjeets. I am getting the exact same problem as rfkova. Let me know if you have figured out a solution yet.

**Comment by surjeets** [comment]
> This may mean that the package is missing, has been obsoleted, or

I will check this matter this week. can you please tell me what version of RPi and Raspberry Pi OS  are you using?

**Comment by surjeets** [comment]
> Hi surjeets. I am getting the exact same problem as rfkova. Let me know if you have figured out a solution yet.

Have you tried 
http://localhost/var/www/html/index.php on your browser? does it show anything?

**Comment by surjeets** [comment]
> Hi surjeets. I am getting the exact same problem as rfkova. Let me know if you have figured out a solution yet.

can you send a screen shot of http://localhost/var/www/html/index.php

**Comment by johndoe2309** [comment]
I have the Raspberry Pi 3B. I was using Raspberry Pi OS a port of Debian (screenshot attached). I have also attached all the errors I get while installing. When I type ./start.sh , nothing happens even though I selected yes when prompted to switch on the camera. It would be great if you could help me out. Thank you so much!
![12](https://user-images.githubusercontent.com/69524529/89926117-04492280-dbca-11ea-8a50-98aad054bb13.jpg)
![14](https://user-images.githubusercontent.com/69524529/89926204-25aa0e80-dbca-11ea-9582-34630bed1aab.jpg)
![16](https://user-images.githubusercontent.com/69524529/89926221-2d69b300-dbca-11ea-99e0-f5e18f451714.jpg)
![18](https://user-images.githubusercontent.com/69524529/89926233-3064a380-dbca-11ea-9dc8-30b0fcaf89df.jpg)
![20](https://user-images.githubusercontent.com/69524529/89926242-322e6700-dbca-11ea-8e53-5d4a24ef8ba8.jpg)
<img width="561" alt="Screenshot 2020-08-11 at 11 55 12 AM" src="https://user-images.githubusercontent.com/69524529/89926255-38244800-dbca-11ea-8baa-75b9ed0de739.png">

**Comment by surjeets** [comment]
> I have the Raspberry Pi 3B. I was using Raspberry Pi OS a port of Debian (screenshot attached). I have also attached all the errors I get while installing. When I type ./start.sh , nothing happens even though I selected yes when prompted to switch on the camera. It would be great if you could help me out. Thank you so much!
> ![12](https://user-images.githubusercontent.com/69524529/89926117-04492280-dbca-11ea-8a50-98aad054bb13.jpg)
> ![14](https://user-images.githubusercontent.com/69524529/89926204-25aa0e80-dbca-11ea-9582-34630bed1aab.jpg)
> ![16](https://user-images.githubusercontent.com/69524529/89926221-2d69b300-dbca-11ea-99e0-f5e18f451714.jpg)
> ![18](https://user-images.githubusercontent.com/69524529/89926233-3064a380-dbca-11ea-9dc8-30b0fcaf89df.jpg)
> ![20](https://user-images.githubusercontent.com/69524529/89926242-322e6700-dbca-11ea-8e53-5d4a24ef8ba8.jpg)
> <img alt="Screenshot 2020-08-11 at 11 55 12 AM" width="561" src="https://user-images.githubusercontent.com/69524529/89926255-38244800-dbca-11ea-8baa-75b9ed0de739.png">

I got this I want to see if anything shows up on the browser.
So, please send a snapshot of this page on your RPi: 
http://localhost/var/www/html/index.php

**Comment by surjeets** [comment]
I got this I want to see if anything shows up on the browser.
So, please send a snapshot of this page on your RPi:
http://localhost/var/www/html/index.php

**Comment by johndoe2309** [comment]
Hi surjeets. I used raspbian stretch instead and was able to get the software installed. However, now when I enter ./start.sh , nothing happens. I have attached screenshots of the terminal window. When I go to the page you listed, I get a message saying this site can't be reached. Please refer to these screenshots. 
![7](https://user-images.githubusercontent.com/69524529/89933193-58590480-dbd4-11ea-83c0-9b22c3b08fcc.jpg)
![6](https://user-images.githubusercontent.com/69524529/89933194-58f19b00-dbd4-11ea-85a8-ad3cb0a66474.jpg)
![5](https://user-images.githubusercontent.com/69524529/89933195-58f19b00-dbd4-11ea-945e-a05762da53db.jpg)
![4](https://user-images.githubusercontent.com/69524529/89933198-58f19b00-dbd4-11ea-8c92-4dd37e1eb2ac.jpg)
![1](https://user-images.githubusercontent.com/69524529/89933211-5c852200-dbd4-11ea-9366-b51fe3c6f4b4.jpg)
![2](https://user-images.githubusercontent.com/69524529/89933221-6018a900-dbd4-11ea-8f5b-e8fd2e43848b.jpg)
![3](https://user-images.githubusercontent.com/69524529/89933228-63139980-dbd4-11ea-9b00-cc2bcc1aa508.jpg)

**Comment by johndoe2309** [comment]
Hi surjeets. Sorry for the many emails. I just need to know the website name where I can access the interface and see the video. Please help. Thank you so much!

**Comment by johndoe2309** [comment]
Hi surjeets. Thanks for your help! I used Raspbian Stretch and it started working!

**Comment by surjeets** [comment]
> Hi surjeets. Thanks for your help! I used Raspbian Stretch and it started working!

Can you please share the screen shot of the working interface for others to see.

**Comment by surjeets** [comment]
@johndoe2309 has it running on Raspbian Stretch.

**Comment by rfkova** [comment]
Hello,

Sorry for the delay. I'm running the latest version of Buster. Just did a fresh install today actually. Silvan Melchior's RPi_Cam_Web_Interface functions and your Animal_Home_Cage does make an accessible video/server but still with some errors like before. 

Punching http://localhost/var/www/html/index.php into the browser yields:
![2020-08-24-134937_1920x1200_scrot](https://user-images.githubusercontent.com/64923232/91084220-41bd9f00-e611-11ea-8ba7-e106a7020bff.png)


You can see the failures to locate packages on the right of the screenshot.

Thank you for your attention :)

**Comment by rfkova** [comment]
Tried installing the old version of Stretch you recommended but I have an RPi4b... and stretch doesn't work on that at all according to internet searches. I'm sort of new to this platform, but do you have any hints about how to go about fixing this on my own?  I realize it's not your responsibility to make this work on a new platform but any information would be valuable.
